### ISSUE TITLE
Feature Update: Displaying Top 5 Classification Results per Seed in Nachet Frontend

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/nachet-frontend#100]
### Summary
Enhance the Nachet Frontend to display the top 5 classification results for each seed, based on the new `topResult` attribute being passed from the Nachet Backend. This feature aims to allow users to view alternative classifications for each detected seed, aiding in identifying misclassifications and improving AI model training.

### Background
The current classification functionality in Nachet Frontend visualizes seeds within images using rectangle boxes, with the backend providing details such as the box dimensions, top label prediction, confidence score, and overlap information. The introduction of a `topResult` attribute by the backend will now include the top 5 classification results for each seed.

### Proposed Functionality
To effectively leverage the `topResult` data, we propose introducing an interactive component that displays the top 5 classification results for a selected seed. Two design approaches are under consideration:
1. **Seed Selection Pop-up:** Clicking on a specific seed box triggers a pop-up to display the top 5 classification results.
2. **Results Table Interaction:** Clicking on an entry in the seed classification results table opens a pop-up with the top 5 results for the selected seed.

Both methods aim to provide detailed insight into the classification process, offering users the ability to flag misclassifications directly. For more details on the design aspect, refer to the discussion with Maxence [here](https://gist.github.com/CFIALeronB/f613cc632610ed93e267237d3832581e).

### Changes to Configuration
- With the introduction of `topResult`, the threshold slider in the results tuner configuration will be removed as it will no longer be utilized.

### Possible Extension
Consider the feasibility of allowing users to directly escalate issues from the classification pop-up, possibly automating the creation of a GitHub issue for further investigation.

### Implementation Considerations
- **UI/UX Design:** The design of the pop-up component should be intuitive and seamlessly integrate with the current interface. It should clearly present the top 5 results, along with their confidence scores and labels.
- **Interaction Design:** Decide on the interaction flow for accessing the top results—whether through direct seed selection or via the results table—and ensure a consistent and user-friendly experience.
- **Error Handling:** Implement robust error handling to manage cases where `topResult` data might be incomplete or missing.
- **Backend Integration:** Ensure that the frontend correctly handles the updated response structure, including the new `topResult` attribute.

### Test Cases Checklist
- [ ] Verify that the top 5 classification results are accurately displayed for seeds upon interaction.
- [ ] Ensure that the pop-up component functions correctly across different devices and screen sizes.
- [ ] Test the user flow for flagging misclassifications directly from the pop-up component.

**Comment by MaxenceGui** [comment]
The plural is good, I also like candidates. From what I understand from the discussion with Amir and Noureddine, a model could eventually send back `n` results and not just 1 or 5. So I would avoid top5 to keep flexibility for the property.

We can also use topN as described in this article comparing top1 vs topN accuracy score:
https://medium.com/nanonets/evaluating-models-using-the-top-n-accuracy-metrics-c0355b36f91b

**Comment by rngadam** [comment]
topN seems good.

"Top N accuracy — Top N accuracy is when you measure how often your predicted class falls in the top N values of your softmax distribution."
