### ISSUE TITLE
Issue with display?: Numbers in unusual places

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-frontend#102]
**Description**
When I took a picture with multiple seeds, results were mostly correct but the display of the labeling numbers 2 and 4 was odd (they are positioned between the two boxes, not each on top of their respective box)

**Expected behavior**
The model will place a box around each seed, with a labeling number above it

**Actual Behavior**
The labels for boxes 2 and 4 are located between the two boxes, and overlap in some views. Also something is odd with box 8, two seeds close together are bounded in the box and the label looks as if there are two numbers superimposed there, as well.

**Supporting Images**
To better understand the issue, please add screenshots:
Results:
![image](https://github.com/ai-cfia/nachet-model/assets/142623921/5ecb65db-87be-425d-8380-0f89746a9327)

* **Source Image**: Attach the actual picture or image used when you encountered the issue.
* 
![WIN_20240306_11_13_25_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/5a3ff846-14b1-48ec-aae7-89fa8640e862)

* **Microscope Settings**:  the microscope settings when the picture was taken.
* 
![WIN_20240306_11_15_30_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/cc26d149-37e6-4b07-8609-4fbda24f4076)

**Comment by rngadam** [comment]
@MaxenceGui please provide explanations when moving issues around layers.

**Comment by MaxenceGui** [comment]
This issue is related to the display of the index, which is a frontend issue instead of a model issue. It's the frontend's responsibility to display the results return by the model.

**Comment by ChromaticPanic** [comment]
Looks like this is Fixed #124 


![Image](https://github.com/ai-cfia/nachet-frontend/assets/78883122/19713d5b-07cc-479e-9609-44dc04265bd8)

**Comment by MaxenceGui** [comment]
Kind of hard to read this one:
![image](https://github.com/ai-cfia/nachet-frontend/assets/96267006/9cb15fb2-9656-49db-a743-d8a8d5cf232a)

- Can we look at a check in the canvas, and if the background where the is about to be written is darker or pale, we have a different color for the text?
- Or should I rework the overlapping to find if the top of a box is inside another one? This way it could be an indicator for you to move the index of the seed at the bottom of the box.

**Comment by ChromaticPanic** [comment]
I see, one easy solution would be to draw a white square background behind any text

then have toggle for labels on or off to see the seeds

**Comment by MaxenceGui** [comment]
Like that!

**Comment by TaranMeyer** [comment]
Some kind of toggle for labels would be nice in a lot of situations anyway---we have talked before about having it highlight selected labels and things like that. Often you want to see quickly which seeds a particular label was applied to.

**Comment by ChromaticPanic** [comment]
> Some kind of toggle for labels would be nice in a lot of situations anyway---we have talked before about having it highlight selected labels and things like that. Often you want to see quickly which seeds a particular label was applied to.

Unrelated but just a thought 
Having a cutout view is possible if a segmentation step is added
![image](https://github.com/ai-cfia/nachet-frontend/assets/78883122/25632b70-7993-4fda-932e-15f60be3bcee)

If used as a preprocessor in the pipeline then background color effects on predictions could be eliminated

Having cutouts also brings endless presentation possibilities

**Comment by MaxenceGui** [comment]
I think you just open a pandora box 😆 @amirardalan9473

**Comment by TaranMeyer** [comment]
The videometer does a kind of cut-out view thing. It is attractive but does have some problems with cutting off bits, or if seeds touch/overlap (since they're not manually placed). Definitely something we could keep in mind for the future. 😅

**Comment by ChromaticPanic** [comment]
Fixed in #136
