### ISSUE TITLE
Migrate Project from create-react-app to Vite

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/nachet-frontend#104]
### Background
The Nachet Frontend project, currently built with create-react-app, aims to improve its build time and developer experience by transitioning to Vite. Vite offers faster builds, hot module replacement, and other benefits that align with our development needs.

### Objective
- Migrate the entire Nachet Frontend project from create-react-app to Vite.
- Ensure that all existing functionalities work seamlessly post-migration.
- Achieve a significant reduction in start-up and build times.
- Maintain or improve the current level of support for development features like hot module replacement, code splitting, and lazy loading.

### Scope
- Analyze and document the necessary changes for the migration.
- Refactor the project configuration to align with Vite's requirements.
- Update build scripts and commands in `package.json`.
- Test the migrated project extensively to ensure all features work as expected.
- Update the documentation to reflect new build and development processes.

### Acceptance Criteria
- The project builds successfully using Vite without errors.
- Development features such as HMR (Hot Module Replacement) work correctly.
- The application runs and functions identically to its create-react-app version.
- Documentation is updated to guide new and existing developers on how to work with the Vite setup.

### Risks and Challenges
- Potential compatibility issues with Vite for specific packages or custom configurations used in the create-react-app setup.
- Ensuring a smooth transition for the development team with minimal disruption to ongoing development efforts.

**Comment by rngadam** [comment]
@CFIALeronB the description should be turned into a checklist so we can quickly understand where we're at with this work.

Also see that there doesn't seem to be a PR associated to this issue.
