### ISSUE TITLE
Add issue template for users specific issues

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/nachet-frontend#106]
### Current Behaviour

Nachet Interactive is a project under the government of Canada and is committed to meeting the [digital standard](https://www.canada.ca/en/government/system/digital-government/government-canada-digital-standards.html) set by the government, which includes designing with users. To receive feedback from users, we have a template available on the nachet-model, which can be used to report model-related issues such as misclassification and false positives. However, users also interact with the frontend interface and may want to report bugs or request new features from the development team.

### Proposed Enhancement

Even if it's possible for users to already report bugs or request new features. we need to keep in mind that our end users are not familiar with GitHub or how our GitHub repository is set up. To help them create an issue, we suggest that they use the current [project board](https://github.com/orgs/ai-cfia/projects/4) and create an issue from there. To help them with the process, we should create two templates on the nachet-frontend repository. One template for reporting bugs in the application, and another template for requesting features. These templates will help our users contribute to the project by guiding them when writing issues that the team can then work on.

### Expected Benefits

Adding these templates will boost the user's contribution to the project and help the development team align their priorities with the needs of our users.

### Implementation Considerations

- Ensure that the templates are easy to understand and find by users

### Checklist

- [x] create the templates (pull request #107) 
- [ ] document the templates
- [ ] train the user

**Comment by rngadam** [comment]
I saw that the checklist is duplicated in the PR.

Maybe here we should think about higher level tasks:

- [ ] create the templates (pull request #107) 
- [ ] document the templates
- [ ] train the user

**Comment by MaxenceGui** [comment]
Like the idea !
