### ISSUE TITLE
Seed not classified: Missed bounding box

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-frontend#118]
**Description**
One of the seeds in this image wasn't detected when running the Swin Transformer model. This is pretty rare for this model unless the seeds are positioned in a way where the bounding boxes would overlap so I thought I'd log it.

**Expected behavior**
All seven seeds on the image are highlighted by a red bounding box.

**Actual Behavior**
The bottom left _Ambrosia psilostachya_ wasn't detected, so it didn't get a bounding box or a seed ID.

**Supporting Images**
To better understand the issue, please add screenshots:
* **Results**: Include a screenshot of the interface showing the classification error or the issue as it appears in your environment.

![Image](https://github.com/ai-cfia/nachet-model/assets/142623921/f2721b92-8ff3-4c80-a50b-a33f4ed18be4)

* **Source Image**: Attach the actual picture or image used when you encountered the issue.
* 

![Image](https://github.com/ai-cfia/nachet-model/assets/142623921/1ea3e864-431d-42c8-b6d6-fb0a04fea511)

**Comment by ChromaticPanic** [comment]
Fixed in #133
