### ISSUE TITLE
Model Feedback Front End Tasks

### ISSUE THREAD

**Issue by ChromaticPanic** [ai-cfia/nachet-frontend#129]
### Issue Description

When seed analysts use Nachet, they should be able to give their retroaction on the result. A pipeline of action needs to be integrated from the Frontend to the database to be able to register the user feedback. These feedbacks can include:

- #103  No seed: The user indicates that the seed detected by the model is not a seed (soil peds for example)
- #40  Wrong classification: The user indicates that the seed is wrongfully classified
  - This feedback can include family, species, and other relevant classifications to the seed
 
 Related to Beck End [#68 Analyst Feedback on Model Result](https://github.com/ai-cfia/nachet-backend/issues/68)
 
### Work to do

Implement a process in the frontend to enable users to give their retroaction. From the backend to the database and the model, send back the result for training purposes and keep track of the model accuracy.

### Acceptance Criteria

- Users can annotate their retroaction on the model results
- Retroaction is saved into the database and helps data scientists with the model training
- Data from retroaction is recorded and saved in the database
- An endpoint in the backend is set up and allows the transit of the data from the frontend to the database and the model

### Front End Tasks
- [ ] Implement the ability for users to give their retroaction in the frontend  
  - Related to https://github.com/ai-cfia/nachet-frontend/issues/40  
  - [x] #156
  - [ ] ~~Provide negative feedback to reject an inference box completely~~
  - [x] #158
  - [x] Provide negative feedback with a correction to the species label (species in training set) 
  - [x] Provide negative feedback with a correction to the species label (species not in training set)
  - [x] Provide negative feedback no seed in the inference box 
  - [x] #167
  - [x] #161
  - [ ] New Component Tests  
  - [ ] Update Documentation  

  
![image](https://github.com/ai-cfia/nachet-frontend/assets/78883122/427a5316-20ed-4030-b2aa-984ae7fcb420)

  
/*******************************************************************************/
- [x] #143
- [x] Implement the no-seed misidentification  
  - Related to https://github.com/ai-cfia/nachet-frontend/issues/103  
- [x] New Component Views  
  - [x] Modal or Callout for feedback  #130 
  - [x] #135
- [x] New Component Logic 
  - [x] Implement positive feedback 
  - [x] #130
    - Pointer tracking to detect canvas location OR  
    - Invisible component divs OR  
    - Replace inference boxes with floating components   
- [x] Front End Data Model for feedback to send to Back End

**Comment by Francois-Werbrouck** [comment]
Question @ChromaticPanic :

During the feedback process, can a user create a new box? (Lets say a seed hasn't been detected) 
Is that use case taken into consideration with the frontend?

**Comment by ChromaticPanic** [comment]
> Question @ChromaticPanic :
> 
> During the feedback process, can a user create a new box? (Lets say a seed hasn't been detected) 
> Is that use case taken into consideration with the frontend?

I haven't added a button to do that, but it should be easy to add.
