### ISSUE TITLE
User Reported Bug: Seed missed for some reason?

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-frontend#132]
**Describe the bug**
Complete seed in image missed/skipped, no bounding box or ID returned. Oddly the program found and ID'd (correctly) the second, partial seed on the right hand side of the image.

**To Reproduce**

1. Load image shared below (.jpg) into model
2. Analyse with Swin Transformer
3. Results returned

**Expected behavior**
The complete seed in the middle of the image would have a red bounding box and label corresponding to its ID. The partial, cutoff seeds might or might not be identified and/or ID'd correctly.

**Screenshots**

![Image](https://github.com/ai-cfia/nachet-frontend/assets/142623921/7f6a710e-2523-49ac-9a8e-a163b2988441)

![Image](https://github.com/ai-cfia/nachet-frontend/assets/142623921/6ec5907d-333d-4597-b83e-2bf7022aa682)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge

**Additional context**
The new model is usually pretty good with segmenting out the seeds, I'm not sure why it would miss this one as it seems pretty well defined to me.

**Comment by MaxenceGui** [comment]
Hi @Taran, I can confirm that the model is returning 2 predictions. However, one of them is below 50% meaning that it won't currently show on the deployed version. I know @ChromaticPanic and @CFIALeronB have work to change that feature.

* https://github.com/ai-cfia/nachet-frontend/pull/125

☝🏻  When they add this change to Nachet, it should show the  missing box.

**Comment by TaranMeyer** [comment]
Awesome, thank you! Good to know why this happens sometimes.

**Comment by ChromaticPanic** [comment]
Fixed in #125
