### ISSUE TITLE
User Reported Bug: ID boxes shifting around

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-frontend#176]
**Describe the bug**
A wonderful new feature has been added where you can click on the taxon in the Results pane (when viewing results by taxon) and it shows you (theoretically) only the red boxes associated with that taxon. Yay! However, when I tried it on the picture below, the boxes shown as taxon 1 when all six were displaying are different than the boxes shown as taxon 1 when you select only taxon 1.

**To Reproduce**

1. Load or take a picture, and classify it.
2. A red bounding box is displayed around each of the six seeds; 4 are identified as *Solanum nigrum*, 2 as *Solanum carolinense*
3. Select *Solanum nigrum* in the results box, and only 4 boxes are displayed. However, in the initial view the bottom-right seed was identified as *Solanum nigrum* and the bottom centre seed was identified as *Solanum carolinense*. But, when we select the *Solanum nigrum* taxon, the bottom centre seed switches to being called *Solanum nigrum*
4. Similarly, if you select *Solanum carolinense* in the results column, the upper middle row seed changes from being called *Solanum nigrum* to being labeled *Solanum carolinense*.
5. You can still mouse over and annotate invisible boxes around the two righthand seeds, however neither is highlighted by selecting either taxon name.
6. There doesn't seem to be a way to go back to having all boxes highlighted.

**Expected behavior**
When switching to view only *Solanum nigrum*, the same boxes/seeds that were assigned to that taxon in the initial view should still display the ID, while the boxes showing *Solanum carolinense* in the initial view should disappear. 

**Screenshots**
Initial view upon classification:
![Image](https://github.com/user-attachments/assets/436f8735-2617-4ba0-ad96-da2ccdb1d719)

View upon selecting "Solanum nigrum" from the Results pane:
![Image](https://github.com/user-attachments/assets/3d789fa4-166e-4fca-bf50-b6d68630cd1d)

View upon selecting "Solanum carolinense" from the Results pane:
![Image](https://github.com/user-attachments/assets/ad83d886-7f08-416f-b689-03b3b846c6aa)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge

**Additional context**
The *Solanum nigrum* IDs are actually all incorrect; all seeds are *Solanum carolinense*. Not sure if that is a factor  in the glitch, though.

**Comment by TaranMeyer** [comment]
Here's a similar result with two very different, correctly ID'd species:



![Image](https://github.com/user-attachments/assets/d5a7fa69-fa3f-45fb-b076-05b2d8c323ad)
![Image](https://github.com/user-attachments/assets/31bef3fa-0950-4d1e-a229-874ede2a8873)
![Image](https://github.com/user-attachments/assets/f203ce26-5abc-449c-b072-b0299655d836)

And the source image for comparison.

**Comment by ChromaticPanic** [comment]
That's really odd behaviour  💀 . I'll take a look.
