### ISSUE TITLE
create architecture diagram

### ISSUE THREAD

**Issue by S-Khos** [ai-cfia/nachet-frontend#24]

**Comment by RussellJimmies** [comment]
https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/693/LOUIS-CFIA-virtual-assistant?anchor=deployment-diagram

**Comment by MaxenceGui** [comment]
Done by @RussellJimmies 


![Image](https://github.com/ai-cfia/nachet-frontend/assets/96267006/8d6c19a6-4617-44f0-9de1-c52716d2f369)

**Comment by rngadam** [comment]
@MaxenceGui where's the source? where do we go to update it?

**Comment by MaxenceGui** [comment]
> @MaxenceGui where's the source? where do we go to update it?

It's on Canvas. @RussellJimmies can you provide a link or a way to access the diagram?

**Comment by RussellJimmies** [comment]
It's in the Ai Lab Graphs project on Canva: 
https://www.canva.com/design/DAFzCw9SgCY/dhjzUTbgNl29QOJIqOXEOA/edit?utm_content=DAFzCw9SgCY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by MaxenceGui** [comment]
![image](https://github.com/ai-cfia/nachet-frontend/assets/96267006/25364cde-9280-48c0-929e-306e26d59be4)

If it doesn't show up at first, be sure to open the bottom panel.
