### ISSUE TITLE
add support for switching between deployed models

### ISSUE THREAD

**Issue by S-Khos** [ai-cfia/nachet-frontend#28]
Prerequisites: 
- [x] #64
- [x] https://github.com/ai-cfia/nachet-backend/issues/30
---
TO-DO:
- [x] Create Model component below Results component with dropdown of deployed models + displaying metadata.
- [x] The list of models retrieves all its data from Nachet's Backend '/model-endpoints-metadata' endpoint.
- [x] When user classifies an image, add model name in request.
- [x] Populate model selection interface with retrieved data.
- [x] Add new test cases and update `testing.md`.
- [x] Document the feature in the project documentation.
---
ACCEPTANCE CRITERIA: 
- [x] Seed group approves UI.
- [x] Can display all deployed models along with corresponding metadata.

**Comment by MaxenceGui** [comment]
Mark as done

![Image](https://github.com/ai-cfia/nachet-frontend/assets/96267006/adb30d9f-b1e1-4067-8034-1bf7f52cb682)
