### ISSUE TITLE
display model specifications in model info popup

### ISSUE THREAD

**Issue by S-Khos** [ai-cfia/nachet-frontend#43]

**Comment by TaranMeyer** [comment]
I also think it's important (for us non-computer folks) to be clear that the model can't identify not-X (as in, it will always ID to one of the species in the model, however low the %. If the species you are trying to identify isn't within the model, it can't tell you that.

**Comment by RussellJimmies** [comment]
No longer will display in a popup, info will be shown when selecting another model. #39
