### ISSUE TITLE
"Classifying" icon or animation

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-frontend#59]
This is very minor, but it would be nice to have some kind of change to the UI after you hit the "classify" button, while the model is working on it. It takes a bit of time and I sometimes find myself forgetting if I've actually clicked it or not. This could take just about any form, (an animation? a change to the appearance of the button? pop-up text that says "classification underway"?) it would just be nice to have something to tell me that it's working on it.

**Comment by MaxenceGui** [comment]
Closing the issue since we have a loading animation:



![Image](https://github.com/ai-cfia/nachet-frontend/assets/96267006/eefe67c7-6954-4f94-8e08-a4ac2c9c6f6a)
