### ISSUE TITLE
Vercel deployment missing for nachet-frontend

### ISSUE THREAD

**Issue by redat97** [ai-cfia/nachet-frontend#77]
While trying to debug an error message from the backend, I noticed that I can't make changes to the frontend without affecting the main URL which could cause issues later if it's not incorporated so need to add the ability to support multiple URL

**Comment by redat97** [comment]
@rngadam I would like to know if we have fully switched to vercel or if we plan on still using gh-pages for nachet-backend, because of how finesse-frontend is setup I thought adding the deployment to vercel wouldn't be an issue but create-react-app makes this very very complicated, I have been trying to debug it for the past hour and I just want to make sure if it's something that will be useful or not. I have an idea of the fix, basically need to set a env variable before the build so that the right script from pacakge.json gets triggered, but just don't want to spend a long time on it for nothing

**Comment by rngadam** [comment]
As discussed, there are solutions to serve from relative paths or specifying the PUBLIC_URL at build time:

https://stackoverflow.com/questions/43011207/using-homepage-in-package-json-without-messing-up-paths-for-localhost

**Comment by redat97** [comment]
> As discussed, there are solutions to serve from relative paths or specifying the PUBLIC_URL at build time:
> 
> https://stackoverflow.com/questions/43011207/using-homepage-in-package-json-without-messing-up-paths-for-localhost

I tried all the solution that were available I don't know if I'm just not knowledgable enough to make it work but I found another solution I will create a PR for it now and tell me if it's okay with you

**Comment by rngadam** [comment]
What did you try and what were the error messages?

**Comment by rngadam** [comment]
also, I see the title here and the PR talks about nachet-backend, but should be nachet-frontend?

**Comment by redat97** [comment]
> also, I see the title here and the PR talks about nachet-backend, but should be nachet-frontend?

copy pasted from the issue I changed both my mistake

**Comment by redat97** [comment]
> What did you try and what were the error messages?

I tried setting the homepage as ".", that didn't change anything, I then tried to add a baseurl like in finesse-frontend and even though in the network tab it made the request to the right URL (meaning https://ai-cfia.github.io/nachet-frontend/static/js/main.3f829c92.js for example) the page still was blank and nothing was appearing, I am guessing maybe because the homepage was still serving to the root but I could be totally wrong I am really not good enough to be able to debug issues like this yet

**Comment by rngadam** [comment]
Have you tried setting `PUBLIC_URL`?

https://create-react-app.dev/docs/advanced-configuration/

Create React App assumes your application is hosted at the serving web server's root or a subpath as specified in package.json (homepage). Normally, Create React App ignores the hostname. You may use this variable to force assets to be referenced verbatim to the url you provide (hostname included). This may be particularly useful when using a CDN to host your application.

**Comment by redat97** [comment]
> Have you tried setting `PUBLIC_URL`?
> 
> https://create-react-app.dev/docs/advanced-configuration/
> 
> **`PUBLIC_URL`**
> 
> Create React App assumes your application is hosted at the serving web server's root or a subpath as specified in package.json (homepage). Normally, Create React App ignores the hostname. You may use this variable to force assets to be referenced verbatim to the url you provide (hostname included). This may be particularly useful when using a CDN to host your application.

i think this one worked
