### ISSUE TITLE
Implement Model Selection/Switching Feature

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/nachet-frontend#93]
### Description

Currently, in the Nachet Frontend, users need the ability to select different models from a provided list. Upon selecting a specific model, the frontend should make an API call to the Nachet Backend, passing the selected model's name as a parameter in the request payload. This feature is crucial for dynamically updating the app's behavior and content based on the chosen model.

### Requirements:

1. **Model Selection Interface**:
   - Implement a user-friendly interface for model selection. This could be a dropdown list or a set of radio buttons, allowing the user to choose from the available models.

2. **State Management**:
   - Manage the state of the selected model in the frontend application. Ensure that the app correctly reflects the currently selected model.

3. **Backend Integration**:
   - Upon model selection, trigger an API call to the Nachet Backend. The model name should be included in the request payload, allowing the backend to respond with model-specific data or actions.

**Comment by rngadam** [comment]
don't forget to set the Projects attribute

**Comment by MaxenceGui** [comment]
Mark as done (PR is closed)


![Image](https://github.com/ai-cfia/nachet-frontend/assets/96267006/570f047f-f97a-4b1c-9c81-6b1314420e76)
